---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prod-db-pvc
  labels:
    username: nriera
    env: prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi
