---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nec-api-deployment
  labels:
    app: nec-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nec-api-deployment
  template:
    metadata:
      labels:
        app: nec-api-deployment
    spec:
      containers:
        - name: nec-api-deployment
          imagePullPolicy: Always
          image: niccoleriera/necelements:latest
          env:
          - name: FLASK_APP
            value: "flask_api.py"
          ports:
          - name: http
            containerPort: 5000
