---
apiVersion: v1
kind: Service
metadata:
  name: prod-db-service
spec:
  type: ClusterIP
  selector:
    app: prod-db-deployment
  ports:
  - name: prod-db-deployment
    port: 6379
    targetPort: 6379
