---
apiVersion: v1
kind: Service
metadata:
  name: prod-api-service
spec:
  type: ClusterIP
  selector:
    app: nec-api-deployment
  ports:
  - name: nec-api-deployment
    port: 5000
    targetPort: 5000
