FROM python:3.9

RUN pip3 install --user Flask==2.0.3 \
		        redis==4.1.4 \
	                hotqueue==0.2.8 \
                        requests \
                        numpy  

COPY ./src/* /app/
COPY ./b67r-rgxc.json /app/b67r-rgxc.json

WORKDIR /app/

ENTRYPOINT ["python3"]
CMD ["flask_api.py"] 
